fixed foreground service issue for audio
lifechurch/nuclei-android pull request #13
Opened 2019-06-25 22:16 UTC by TheKaseys

This fixes the audio stopping issue related to us stopping foreground services improperly since Doze updates.

2019-06-26 15:10 UTC, jakeaaron requested changes
I think we still need to stop the service somewhere..

2019-06-26 15:40 UTC, kylebrock commented on nuclei-android/src/main/java/nuclei3/media/MediaNotificationManager.java
>              LOG.d("updateNotificationPlaybackState. cancelling notification!");
remove this

2019-06-27 00:42 UTC, kylebrock commented on nuclei-android/src/main/java/nuclei3/media/MediaNotificationManager.java
> +            mNotificationManager.notify(NOTIFICATION_ID, notification);
make sure mNotificationManager isn't null

2019-06-27 00:44 UTC, kylebrock commented on nuclei-android/src/main/java/nuclei3/media/playback/ExoPlayerPlayback.java
> -        mService.stopForeground(true);
Are you sure this is necessary?  If it is, you should probably update the comment.

2019-06-27 15:30 UTC, TheKaseys commented on nuclei-android/src/main/java/nuclei3/media/playback/ExoPlayerPlayback.java
> -        mService.stopForeground(true);
It is necessary because we are calling relaxResources() when exoplayer stops, temporarily stops, pauses, seeks, or has an error. unless you want me to change when relaxResources() is called.

2019-07-08 18:24 UTC, jakeaaron approved these changes

2019-07-08 18:26 UTC, jakeaaron approved these changes

2019-07-08 18:33 UTC, merged